apiVersion: v1
kind: Pod
metadata:
  name: broadsea
  labels:
    app: web
spec:
  containers:
    - name: broadsea-methods
      image: ohdsi/broadsea-methodslibrary
      ports:
        - containerPort: 8787
        - containerPort: 6111
      volumeMounts:
      - name: keys
        mountPath: "/tmp/drivers/"
        readOnly: true
    - name: broadsea-webtools
      image: ohdsi/broadsea-webtools
      ports:
        - containerPort: 8080
      volumeMounts:
      - name: keys
        mountPath: "/tmp/drivers/"
        readOnly: true
      env:
      - name: WEBAPI_URL
        value: http://localhost:8080
      - name: env
        value: webapi-postgresql
      - name: datasource.driverClassName
        value: org.postgresql.Driver
      - name: datasource.url
        value: jdbc:postgresql://192.168.99.100:5432/postgres
      - name: datasource.cdm.schema
        value: cdm
      - name: datasource.ohdsi.schema
        value: ohdsi
      - name: datasource.username
        value: postgres
      - name: datasource.password
        value: secret-user-password
      - name: spring.jpa.properties.hibernate.default_schema
        value: ohdsi
      - name: spring.jpa.properties.hibernate.dialect
        value: org.hibernate.dialect.PostgreSQLDialect
      - name: spring.batch.repository.tableprefix
        value: ohdsi.BATCH_
      - name: flyway.datasource.driverClassName
        value: org.postgresql.Driver
      - name: flyway.datasource.url
        value: jdbc:postgresql://192.168.99.100:5432/postgres
      - name: flyway.schemas
        value: ohdsi
      - name: flyway.placeholders.ohdsiSchema
        value: ohdsi
      - name: flyway.datasource.username
        value: postgres
      - name: flyway.datasource.password
        value: secret-user-password
      - name: flyway.locations
        value: classpath:db/migration/postgresql
  volumes:
  - name: keys
    secret:
      secretName: ohdsi-bigquery
